Eduhelx
helxplatform/appstore pull request #129
Opened 2021-06-10 20:11 UTC by Acharya-Saurya

Added eduhelx brand to files (similar to cmas).

2021-06-11 01:31 UTC, ismagilani requested changes

2021-06-11 01:31 UTC, ismagilani commented on appstore/core/templates/base.html
> +            <a href="/"><img class="navbar-brand" id="img-brand-eduhelx-logo" src="{% static "images/heal/heal-social-logo.png" %}" <!--TBD -->
reference brand directory here i.e. images/eduhelx/logo-name.png

2021-06-11 01:31 UTC, ismagilani commented on appstore/appstore/settings/eduhelx_settings.py
> +    logo_url="/static/images/cmas/cmas-logo.png", #TBD
use an eduhelx directory under static/images

2021-06-11 01:31 UTC, ismagilani commented on appstore/core/templates/base.html
> +            <a href="/"><img class="navbar-brand" id="img-brand-eduhelx-logo" src="{% static "images/heal/heal-social-logo.png" %}" <!--TBD -->
use images/eduhelx/ and eduhelx logo which I will request from marketing

2021-06-11 01:31 UTC, ismagilani commented on appstore/core/views.py
> +            "logo": "heal-social-logo.png" #TBD
need correct logo reference

2021-06-11 01:32 UTC, ismagilani commented
@Acharya-Saurya please send an email to Marcus Anderson and ask him to design a logo for EduHeLx instance.  Tell him that it is for HeLx platform and for a data science course at UNC.  He may have one we can already use.  Please CC me on the email.

2021-06-14 16:33 UTC, closed without merging

2021-06-14 16:33 UTC, Acharya-Saurya commented
Recreating eduhelx branch